// API-key auth for the cloud worker. Mirrors the key format used by the main app
// (src/shared/utils/apiKey.js):  sk-{machineId}-{keyId}-{crc8}
//   - crc8 = first 8 hex chars of HMAC-SHA256(machineId + keyId, API_KEY_SECRET)
// Web Crypto (crypto.subtle) is async in Workers, so parseApiKey is async.
//
// IMPORTANT: env.API_KEY_SECRET MUST match the app's API_KEY_SECRET, otherwise
// keys generated by the dashboard will fail CRC validation here.

const DEFAULT_SECRET = "endpoint-proxy-api-key-secret";

function getSecret(env) {
  return (env && env.API_KEY_SECRET) || DEFAULT_SECRET;
}

// Constant-time-ish compare for short hex digests.
function timingSafeEqualStr(a, b) {
  if (typeof a !== "string" || typeof b !== "string" || a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function hmacSha256Hex(secret, message) {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, enc.encode(message));
  return [...new Uint8Array(sig)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** Extract a Bearer token from the Authorization header (sync). Returns null if absent/not Bearer. */
export function extractBearerToken(request) {
  const auth = request?.headers?.get?.("Authorization") || "";
  if (!auth) return null;
  const m = /^Bearer\s+(.+)$/i.exec(auth.trim());
  return m ? m[1].trim() : null;
}

/**
 * Parse an API key into { machineId, keyId, isNewFormat } or null.
 *  - New format: sk-{machineId}-{keyId}-{crc8}  (CRC validated via HMAC)
 *  - Old format: sk-{random8}                    (no machineId, no CRC)
 * @param {string} apiKey
 * @param {object} [env] - Worker env (for API_KEY_SECRET)
 */
export async function parseApiKey(apiKey, env) {
  if (!apiKey || typeof apiKey !== "string" || !apiKey.startsWith("sk-")) return null;
  const parts = apiKey.split("-");

  if (parts.length === 4) {
    const [, machineId, keyId, crc] = parts;
    const expected = (await hmacSha256Hex(getSecret(env), machineId + keyId)).slice(0, 8);
    if (!timingSafeEqualStr(crc, expected)) return null;
    return { machineId, keyId, isNewFormat: true };
  }

  if (parts.length === 2) {
    return { machineId: null, keyId: parts[1], isNewFormat: false };
  }

  return null;
}

/** True when the key parses and (for new-format keys) the CRC is valid. */
export async function verifyApiKey(apiKey, env) {
  return (await parseApiKey(apiKey, env)) !== null;
}

/** Sync check for the new (machineId-embedding) key shape — no CRC validation. */
export function isNewFormatKey(apiKey) {
  return typeof apiKey === "string" && apiKey.startsWith("sk-") && apiKey.split("-").length === 4;
}
